SUBSCRIPTION_KEY = # AZURE FACE API SUBSCRIPTION KEY
BASE_URL = # AZURE FACE API URL
PERSON_GROUP_ID = # AZURE FACE API GROUP ID
SQL_SERVER_ADDRESS = # AZURE SQL DATABASE ADDRESS
DATABASE_NAME = # AZURE SQL DATABASE NAME
DATABASE_USERNAME = # AZURE SQL DATABASE USERNAME
DATABASE_PASSWORD = # AZURE SQL DATABASE PASSWORD
